export default function HomePage() {
  return (
    <main>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
      <div>
        <h1>Codeflix</h1>
      </div>
    </main>
  )
}